# Generated by Django 3.0.4 on 2020-03-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duenios', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duenio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='duenios.Duenio'),
        ),
    ]
