# Generated by Django 3.0.4 on 2020-03-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0002_servicio_duenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('servicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio')),
            ],
        ),
    ]
