# Generated by Django 3.0.4 on 2020-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLaPazVip', '0002_auto_20200329_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='zona',
            field=models.CharField(max_length=500),
        ),
    ]
